cat \
../model/crear_base_de_datos.sql \
../model/region.sql \
../model/tipo_de_persona.sql \
../model/tipo_de_empresa.sql \
../model/tipo_de_perfil.sql \
../model/beneficiario.sql \
../model/proyecto.sql \
../model/sexo.sql \
../model/persona.sql \
../model/miembro.sql \
../model/colaborador.sql \
../model/usuario.sql \
../model/consorcio.sql \
../model/financiador.sql \
../model/estado_de_fondo.sql \
../model/tipo_de_beneficio.sql \
../model/instrumento.sql \
../model/resultado.sql \
../model/postulacion.sql \
../model/idea.sql \
../model/propuesta.sql \
../model/insertar-datos.sql \
../model/vistas-estaticas.sql \
> ../database.sql
