cat \
crear_base_de_datos.sql \
region.sql \
tipo_de_persona.sql \
tipo_de_empresa.sql \
tipo_de_perfil.sql \
beneficiario.sql \
proyecto.sql \
sexo.sql \
persona.sql \
miembro.sql \
colaborador.sql \
usuario.sql \
consorcio.sql \
financiador.sql \
estado_de_fondo.sql \
tipo_de_beneficio.sql \
instrumento.sql \
resultado.sql \
postulacion.sql \
idea.sql \
propuesta.sql \
insertar-datos.sql \
| sudo mariadb
