# Junta todos los archivos SQL y los combina en un unico archivo
cat \
../models/crear_base_de_datos.sql \
../models/region.sql \
../models/tipo_de_persona.sql \
../models/tipo_de_empresa.sql \
../models/tipo_de_perfil.sql \
../models/beneficiario.sql \
../models/proyecto.sql \
../models/sexo.sql \
../models/persona.sql \
../models/miembro.sql \
../models/colaborador.sql \
../models/usuario.sql \
../models/consorcio.sql \
../models/financiador.sql \
../models/estado_de_fondo.sql \
../models/tipo_de_beneficio.sql \
../models/instrumento.sql \
../models/resultado.sql \
../models/postulacion.sql \
../models/idea.sql \
../models/propuesta.sql \
../models/insertar-datos.sql \
../models/vistas-estaticas.sql \
> ../database.sql
